oauth2:
  kakao:
    client-id: 628ed7ebd5ae9ca490639c88d1ff40fe
    client-secret: dTcelI2SjqCm3mi7E2BJNZST7KiKIfom
    redirect-uri: http://localhost:3000/oauth2/callback/kakao
  google:
    client-id: 342402058366-uqaknkbu14juso56958312iqoq723n0m.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:3000/oauth2/callback/google
  naver:
    client-id: g9kUOaGUwAIFWV5mbw2w
    client-secret: dWZ6O8BaW2
    redirect-uri: http://localhost:3000/oauth2/callback/naver