logging:
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql.BasicBinder: debug
        com.leesh: debug
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always