server:
  port: 8082
  servlet:
    context-path: /prod

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql.BasicBinder: debug
        com.leesh: debug
    com.leesh.quiz.api.quiz.dao.QuizDao: debug

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 # OneToMany 관계 조회 시, 쿼리 한 번으로 최적화
    open-in-view: false # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시, 하나의 파일 크기를 10MB로 제한
      max-request-size: 100MB # 파일 업로드 요청 시, 전체 요청 크기를 100MB로 제한
  aop:
    proxy-target-class: false # Filter의 경우 JDK 기반의 프록시를 사용하도록 설정
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 2000

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml

token:
  secret: ENC(ZWPxWyobK729VrfW9s8GAqg5yAiHA6Cl7w7P3PQbc9QP9b0BZU0yJLLaRsKZKT45tFwrt/LFNoPeAI6fqRIh5IHDOTtwVEErnRzQsU1zIgIQ/SRzcFA2ZBIQIcgEAAywfbi6GVtRGvykI/W//LsZ1LFVb8WWBRZwc6WrAzxKyUmRrrbUdkl5lGg7FegQHm9W)
  access-token-expiration-time: 10000  # 15분 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2주 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)

oauth2:
  kakao:
    client-id: ENC(+qwXTMtp0ldynQquCCT5E3saeJ8wGyZt8qc8oErTQfidIU/k68jpHgyUbr/Z6vSD)
    client-secret: ENC(/Ti7JS3XCc9dXqianikAXLkVnYW62cdrgd5MP6VpxuSkuSOKK5BRnwJBu+yMcRPK)
    redirect-uri: ENC(Q/xHiaIH9MdG3SZ1V+8TN0kurPNNm8zZgBzCNHyv4bcI5M1O+rYS/hmR9yyj5zvq+aeQibnYKSI=)
  google:
    client-id: ENC(RbSPR65Q5gbvHn6v8qCjOjbo/rPoU/iVZAWx1o0O6JCWzWfs54JLBkV4i7/OOY0pSY1MY9gSb6abUdL2kJ5pzovFCYZ3H8QBnwOGmLLehUFaNs3N4cSGyA==)
    client-secret: ENC(3tgUQVepvdHtsXkzm+yGtAFh/X6Wf8l7N0bcODBW5FyPxfG+T203zdzEYFLtE8FS)
    redirect-uri: ENC(Q/TUiycA/lXt2zV+1JJb7zp1Ct518DxL6uaX8eXi8opWaMtamiHN3c0d9OWrWv0az5tttfslkJ0=)
  naver:
    client-id: ENC(T9U9GbshI2M2rxHtb0q1szQ1gWYsaN/z2aDhwabsSOw=)
    client-secret: ENC(rosNjvu/3I1sS9RkH1WlG/dA/JlS5Kgk)
    redirect-uri: ENC(CZZFpqwoEZqTXGqOuejBFSENIQaz1bkBGMMPlShljzyP45fLu9O+EbWWAo5QcRtZfdnDIMOgVQ4=)
